__use_generic_keys__ = { url = "socialNetwork" }

team_order = [
  "Executive Committee",
  "Business Development",
  "Brand Directors",
  "Technology & Analytics",
  "Content",
  "Retail Media",
  "Seller Performance, Retail & Distribution",
  "Admin",
  "Creative & Digital Marketing",
]

# [CEO]
# email = "j.deguigne@e-comas.com"
# Name = "Jérôme de Guigné"
# Title = "Founder & CEO"
# bio = """\
#     Jérôme specialises in helping global brands grow their distribution on \
#     and through Amazon. His wealth of ecommerce expertise comes from 20 years \
#     of sales and international distribution experience in Europe, Asia and \
#     North America. Jérôme focuses on real-world proven solutions, with \
#     results as great as multiplying revenue by five times or more within two \
#     years.\
#   """
# pictureUrl = "/images/team/Teams-New-Jérôme.png"
# url.LinkedIn = "https://www.linkedin.com/in/jeromedeguigneamazonexpert/"
# # url.Medium = "https://amazon-expert.medium.com/"
# url.YouTube = "https://www.youtube.com/channel/UC8FEB3vsicxo5gI3mtdl50A"

# [COO]
# Name = "Amalia Sebakunzi"
# Title = "Chief Operating Officer"
# bio = """\
#     Amalia is a business leader with over 14 years of international experience \
#     spanning a broad range of industries, including FMCG, Food, Beauty, \
#     Luxury, Ecommerce and Digital Health. Amalia joined e-Comas as Chief \
#     Operating Officer in 2021, having worked in Nigeria for three years \
#     heading up strategic marketing activities for one of the world’s leading \
#     food brands. With over a decade of sales and marketing expertise, Amalia \
#     has a wealth of knowledge to help brands succeed on all online \
#     marketplaces.\n\
#   """
# quote = "\"Any business not investing time & ressources on e-commerce right now is missing out on the opportunity of the century\""
# pictureUrl = "/images/team/amalia.png"
# url.LinkedIn = "https://www.linkedin.com/in/amaliawidder/"
# url.YouTube = "https://www.youtube.com/watch?v=0-TBc8-UC1w"

[[team_member]]
email = "j.deguigne@e-comas.com"
Name = "Jérôme de Guigné"
Title = "Founder & CEO"
Team = "Executive Committee"
bio = """\
    Jérôme specialises in helping global brands grow their distribution on \
    and through Amazon. His wealth of ecommerce expertise comes from 20 years \
    of sales and international distribution experience in Europe, Asia and \
    North America. Jérôme focuses on real-world proven solutions, with \
    results as great as multiplying revenue by five times or more within two \
    years.\
  """
pictureUrl = "/images/team/Teams-New-Jérôme.png"
url.LinkedIn = "https://www.linkedin.com/in/jerom$edeguigneamazonexpert/"
# url.Medium = "https://amazon-expert.medium.com/"
url.YouTube = "https://www.youtube.com/channel/UC8FEB3vsicxo5gI3mtdl50A"
priority = 4

[[team_member]]
Name = "Nazlı Kayıkçı"
Title = "COO"
Team = "Executive Committee"
quote = "Identifying your gaps and needs at the beginning of your ecom journey is the greatest favor that you can do for your brand'"
pictureUrl = "/images/team/Teams-New-Nazli.png"
url.LinkedIn = "https://www.linkedin.com/in/nazl%C4%B1-ipek-kay%C4%B1k%C3%A7%C4%B1-86644a23/"
url.YouTube = "https://www.youtube.com/watch?v=nN8QWZ5S7-M"
priority = 3

[[team_member]]
Name = "Janis Dechamps"
Team = "Admin"
Title = "Head of Finance and Administration"
url.LinkedIn = "https://lu.linkedin.com/in/janis-dechamps-97b0295"
pictureUrl = "/images/team/Teams-New-Janis.png"
priority = 2

[[team_member]]
Name = "Claudiu Clement"
Title = "CTO"
Team = "Executive Committee"
quote = "\"Building a great experience for the right client is the main driver of success in ecommerce.\""
pictureUrl = "/images/team/Teams-New-Claudiu.png"
url.LinkedIn = "https://www.linkedin.com/in/claudiu-clement/"
url.YouTube = "https://www.youtube.com/watch?v=LgI0R1hmyCE&ab_channel=e-Comas"
priority = 1


[[team_member]]
Name = "Agu\u00e8ne Sambou"
Title = "PIM Team Lead"
Team = "Technology & Analytics"
quote = "\"Whithout challenge, There Isn't Change\""
pictureUrl = "/images/team/Aguene.png"
url.LinkedIn = "https://www.linkedin.com/in/agu%C3%A8ne-sambou/"
priority = 2


[[team_member]]
Name = "Nagapooja Ramesh"
Title = "Implementation Specialist"
Team = "Technology & Analytics"
quote = "\"When we really pay attention,everything is your teacher.\""
pictureUrl = "/images/team/Nagapooja.png"
url.LinkedIn = "https://www.linkedin.com/in/nagapooja-ramesh-a77850136"


[[team_member]]
Name = "Michael Baron"
Team = "Technology & Analytics"
Title = "PIM Consultant"
pictureUrl = "/images/team/Michael Baron.png"
url.LinkedIn = "https://www.linkedin.com/in/michael-baron-a0808822/"
priority = 0


[[team_member]]
Name = "Alexandre Zambeaux"
Title = "Head of EMEA Business Development"
Team = "Business Development"
quote = "\u201cKnow the rules well, so you can break them effectively.\u201d"
pictureUrl = "/images/team/Alexandre-Zambeaux.png"
contactPage = true
url.LinkedIn = "https://www.linkedin.com/in/alexandrezambeaux/"
url.YouTube = "https://www.youtube.com/watch?v=lW1ffcwiyP8"
url.Calendly = "https://calendly.com/alexz-ecommerce"

[[team_member]]
Name = "Devin booth"
Team = "Business Development"
Title = "Director of Sales"
pictureUrl = "/images/team/Teams-New-Devin.png"
contactPage = true
url.Calendly = "https://calendly.com/d-booth-e-comas"
url.LinkedIn = "https://www.linkedin.com/in/devin-booth-amazon-expert/"


[[team_member]]
Name = "Riley Bell"
Title = "Senior Account Director"
Team = "Brand Directors"
quote = "\"eCommerce is an ever evolving landscape with fresh challenges and new opportunities emerging each day\""
pictureUrl = "/images/team/Riley.png"
url.LinkedIn = "https://www.linkedin.com/in/bellriley/"
url.YouTube = "https://www.youtube.com/watch?v=miLaUlqNruc"
priority = 3


[[team_member]]
Name = "Sven Jacosben Diaz"
Title = "Account Director"
Team = "Brand Directors"
quote = "You miss 100% of the shots you don't take"
pictureUrl = "/images/team/Sven.png"
url.LinkedIn = "https://www.linkedin.com/in/sven-jacobsen-diaz/"
priority = 2


[[team_member]]
Name = "Anchit Abraham"
Team = "Brand Directors"
Title = "Senior Account Specialist"
pictureUrl = "/images/team/Anchit.png"
url.LinkedIn = "https://www.linkedin.com/in/anchitabraham/"


[[team_member]]
Name = "Marius Popov"
Team = "Seller Performance, Retail & Distribution"
Title = "Head of Distribution"
url.LinkedIn = "https://www.linkedin.com/in/marius-popov-488a5752/"
pictureUrl = "/images/team/Teams-New-MariusPopov.png"
priority = 3


[[team_member]]
Name = "Richard Ravichandar"
Title = "Senior Account Director"
Team = "Brand Directors"
quote = "We CARE for your business like no one else did. We GROW your business like never before."
pictureUrl = "/images/team/Teams-New-Richard.png"
url.LinkedIn = "https://www.linkedin.com/in/richard-ravichandar-a1929a50/"
priority = 2


[[team_member]]
Name = "Charl\u00e8ne Gr\u00e9goire"
Title = "Account Director"
Team = "Brand Directors"
quote = "\"Every problem is a gift - without problems we would not grow\""
pictureUrl = "/images/team/Teams-New-Charlène.png"
url.LinkedIn = "https://www.linkedin.com/in/charlene-gregoire"
url.YouTube = "https://www.youtube.com/watch?v=DTdtGuAuY6E"
priority = 2


[[team_member]]
Name = "Seval Solmaz"
Title = "Content team Lead"
Team = "Content"
pictureUrl = "/images/team/Team-Template-Seval.png"
priority = 3

[[team_member]]
Name = "Antonio Vicedo Mart\u00ednez"
Title = "Head of Services"
Team = "Technology & Analytics"
quote = "\"In a world that moves and evolves as fast as e-commerce, make sure to save some time to reflect and plan\""
pictureUrl = "/images/team/Teams-New-Antonio.png"
url.LinkedIn = "https://www.linkedin.com/in/antoniovicedo/"
priority = 3

[[team_member]]
Name = "Cristian Avendano"
Title = "Senior Content Expert"
Team = "Content"
pictureUrl = "/images/team/Teams-New-Cristian.png"
priority = 2

[[team_member]]
Name = "Richard Arokiaraj"
Team = "Content"
Title = "Content Specialist"
quote = "Leap, and the net will appear."
url.LinkedIn = "https://www.linkedin.com/in/richie7/"
pictureUrl = "/images/team/Teams-New-RichardArokiaraj.png"


[[team_member]]
Name = "Henintsoa Andriatianarivo"
Title = "Content Specialist"
Team = "Content"
quote = "\"A smooth sea never made a skilled sailor.\""
pictureUrl = "/images/team/Teams-New-Henintsoa.png"
url.LinkedIn = "https://www.linkedin.com/in/henintsoa/"
url.YouTube = "https://www.youtube.com/watch?v=rmB-6-x9spA"


[[team_member]]
Name = "Manasa Krishnamurthy"
Team = "Content"
Title = "Senior Content Specialist"
quote = "You can not shake hands with clenched fist"
url.LinkedIn = "https://www.linkedin.com/in/manasa-k-53a084197/"
pictureUrl = "/images/team/Manasa.png"


[[team_member]]
Name = "Mireille Rasoa"
Title = "Content Specialist"
Team = "Content"
quote = "\"You are your only limit\""
pictureUrl = "/images/team/Teams-New-Mireille_.png"
url.LinkedIn = "https://www.linkedin.com/in/mireille-rasoa-605194215/"

[[team_member]]
Name = "Tiffany Lemprière"
Title = "Head of Performance Marketing"
Team = "Retail Media"
pictureUrl = "/images/team/Teams-New-TiffanyLemprière.png"
priority = 2


# [[team_member]]
# Name = "Mehul James"
# Team = "Retail Media"
# Title = "Advertising Specialist"
# url.LinkedIn = "https://www.linkedin.com/in/mehul-james-86654a10a"
# pictureUrl = "/images/team/Mehul.png"


[[team_member]]
Name = "Sandeep Venkataraj"
Title = "Retail and distribution Specialist"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Sandeep.png"


[[team_member]]
Name = "Misa Manass\u00e9"
Title = "Office Manager"
Team = "Admin"
quote = "\"Persistence is the path to success\" C Chaplin"
pictureUrl = "/images/team/Teams-New-Misa.png"
url.LinkedIn = "https://www.linkedin.com/in/misa-manass%C3%A9-3994a4225/"


[[team_member]]
Name = "Oscar Samson"
Title = "Head of India Operations and HR"
Team = "Admin"
quote = "Success is the sum of small efforts repeated day in and day out"
pictureUrl = "/images/team/Teams-New-Oscar.png"
url.LinkedIn = "https://www.linkedin.com/in/oscar-samson"


[[team_member]]
Name = "Audrey Palma"
Title = "Administrative & accounting officer"
Team = "Admin"
pictureUrl = "/images/team/Teams-New-Audrey.png"


[[team_member]]
Name = "Jessica Barton"
Title = "Social & Copywriting Manager"
Team = "Creative & Digital Marketing"
pictureUrl = "/images/team/Teams-New-JessB.png"


[[team_member]]
Name = "Jessamy Chapman"
Title = "Press Manager"
Team = "Creative & Digital Marketing"
pictureUrl = "/images/team/Jessamy-Chapman.png"


[[team_member]]
Name = "Joel Young"
Title = "Lead Creative"
Team = "Creative & Digital Marketing"
quote = "Be happy in everything you do. That's most important. And give a pet a home."
pictureUrl = "/images/team/Joel.png"


[[team_member]]
Name = "Mario Jeffrin"
Title = "Designer"
Team = "Creative & Digital Marketing"
pictureUrl = "/images/team/Mario.png"


[[team_member]]
Name = "Stéphane du Hamel"
Title = "Front End and Back End Engineer"
Team = "Creative & Digital Marketing"
pictureUrl = "/images/team/Team-Template-Stéphane.png"


[[team_member]]
Name = "Manu Mathew"
Team = "Brand Directors"
Title = "Senior Account Specialist"
quote = "Alone we can do so little, together we can do so much"
pictureUrl = "/images/team/Teams-New-Manu.png"
url.LinkedIn = "https://www.linkedin.com/in/manujoymathew"
url.YouTube = "https://www.youtube.com/watch?v=37Q_2Ta4BRY"

# [[team_member]]
# Name = "Preethi Gopakumar"
# Team = "Content"
# Title = "Content Specialist"
# url.LinkedIn = "https://www.linkedin.com/in/preethi-gopakumar-2588b6138/"
# pictureUrl = "/images/team/Teams-New-Preethi.png"

[[team_member]]
Name = "Kevin Abraham Suresh"
Team = "Content"
Title = "Content Specialist"
url.LinkedIn = "https://www.linkedin.com/in/kevin-abraham-suresh-965730b8/"
pictureUrl = "/images/team/Teams-New-Kevin.png"

[[team_member]]
Name = "Arjun Narayan"
Team = "Retail Media"
Title = "Senior Advertising Specialist"
pictureUrl = "/images/team/Arjun.png"

# [[team_member]]
# Name = "Hedi Guembri"
# Team = "Brand Directors"
# Title = "Account Director"
# pictureUrl = "/images/team/Teams-New-Hedy.png"
# url.LinkedIn = "https://www.linkedin.com/in/hedi-guembri/"


# [[team_member]]
# Name = "Josh Gibson"
# Team = "Brand Directors"
# pictureUrl = "/images/team/Teams-New-Josh.png"
# Title = "Account Director"
# # url.LinkedIn = ""

# [[team_member]]
# Name = "Nikoleta Spasic"
# Team = "Content"
# Title = "Content Specialist"
# url.LinkedIn = "https://www.linkedin.com/in/nikoleta-spasic-929145197/"
# pictureUrl = "/images/team/Teams-New-Nikoleta.png"

[[team_member]]
Name = "Parker Amstutz"
Title = "Head of Creatives"
Team = "Creative & Digital Marketing"
pictureUrl = "/images/team/Teams-New-Parker.png"
url.LinkedIn = "https://www.linkedin.com/in/parker-amstutz-86493473/"

[[team_member]]
Name = "Loris Voyer"
Title = "Head of Digital Marketing"
Team = "Creative & Digital Marketing"
pictureUrl = "/images/team/Teams-New-Loris.png"
url.LinkedIn = "https://www.linkedin.com/in/loris-voyer/"

[[team_member]]
Name = "Yusuf Kayikci"
Title = "Distribution Specialist"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Teams-New-Yusuf Kayikci.png"

# [[team_member]]
# Name = "Radmila Zogovic"
# Title = "Retail Specialist"
# Team = "Seller Performance, Retail & Distribution"
# pictureUrl = "/images/team/Teams-New-Radmila.png"

[[team_member]]
Name = "Tijana Stepovic"
Title = "Content Specialist"
Team = "Content"
pictureUrl = "/images/team/Team-Template-Tijana.png"

[[team_member]]
Name = "Manasa Murthy"
Title = "Senior Account Specialist"
Team = "Brand Directors"
url.LinkedIn = "https://www.linkedin.com/in/manasa-k-53a084197/"
pictureUrl = "/images/team/Manasa.png"


[[team_member]]
Name = "Annette Lees"
Title = "Head of UK Growth"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/teams-new-annettelees.png"

[[team_member]]
Name = "Tori Thomas"
Title = "Marketing Executive"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Teams-New-Tori.png"

[[team_member]]
Name = "Mick Swift"
Title = "Warehouse Manager"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Teams-New-Mick.png"

[[team_member]]
Name = "Martyn Walley"
Title = "Warehouse Assistant Manager"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Team-Template-MartynW.png"

[[team_member]]
Name = "Rachel Adamberry"
Title = "Customer Service Executive"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Teams-New-Rachel.png"

[[team_member]]
Name = "Shanmuga Priya"
Title = "Advertising specialist"
Team = "Retail Media"
pictureUrl = "/images/team/Team-Template-Shanmuga-Priya.png"

[[team_member]]
Name = "El Idrissi Kawtar"
Title = "Account Director"
Team = "Brand Directors"
pictureUrl = "/images/team/Team-Template-EL-IDRISSI.png"

[[team_member]]
Name = "Fred Rainjonneau"
Title = "General Manager Distribution"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Team-Template-Fred.png"

[[team_member]]
Name = "Marc Villaseca"
Title = "Senior Ads Strategist"
Team = "Retail Media"
pictureUrl = "/images/team/Team-Template-Marc.png"

[[team_member]]
Name = "Jack Turner"
Title = "Group Head of Operations"
Team = "Executive Committee"
pictureUrl = "/images/team/Team-Template-Jack.png"

[[team_member]]
Name = "Seval Solmaz"
Title = "Head of strategy"
Team = "Brand Directors"
priority = 4
pictureUrl = "/images/team/Team-Template-Seval.png"

[[team_member]]
Name = "Joe Swanston"
Title = "Business & Category Manager"
Team = "Seller Performance, Retail & Distribution"
pictureUrl = "/images/team/Team-Template-JoeS.png"
